// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBrkVY9KrhSpPuQkdm2nk8zFW0qhCuGEM',
    appId: '1:511513642938:web:6f00a6f3a9f78d352cbf83',
    messagingSenderId: '511513642938',
    projectId: 'tripura-news-officials',
    authDomain: 'tripura-news-officials.firebaseapp.com',
    databaseURL: 'https://tripura-news-officials.firebaseio.com',
    storageBucket: 'tripura-news-officials.appspot.com',
    measurementId: 'G-T8M7K2QXEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwLM7TloC0DaJE4fiYcHRPAyxrM-jXns',
    appId: '1:511513642938:android:7d6798e414ce770f2cbf83',
    messagingSenderId: '511513642938',
    projectId: 'tripura-news-officials',
    databaseURL: 'https://tripura-news-officials.firebaseio.com',
    storageBucket: 'tripura-news-officials.appspot.com',
  );
}
